name: bloc_study
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: lib/login/packages/authentication_repository
  user_repository:
    path: lib/login/packages/user_repository

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
